### ISSUE TITLE
Add an example

### ISSUE THREAD

**Issue by EmmanuelMess** [clay-ui-rs/clay#13]
Add example code and screenshot.

**Comment by Mathys-Gasnier** [comment]
There is a temporary test in `lib.rs` that shows you how you can use the lib, but yes we need to add an example.
A warning, the binding is not fully finished yet, some parts are not even implemented in the rust layer

**Comment by Mathys-Gasnier** [comment]
Even if it's only a small example, I will close this issue, more examples will be added soon.
