### ISSUE TITLE
Crate name

### ISSUE THREAD

**Issue by emoon** [clay-ui-rs/clay#3]
I suggest it should be called `clay-ui-layout` instead of `rust_clay` thoughts?

**Comment by Mathys-Gasnier** [comment]
Imo `clay-ui` would be enough, since we could also support renderers with feature flags (raylib, macroquad, etc)

**Comment by emoon** [comment]
For me `clay-ui` feels like a "full ui" system while it's not. The description of clay is `Clay (short for C Layout) is a high performance 2D UI layout library.`

**Comment by emoon** [comment]
Cool. I will do a pr to update the name (also it's not taken on `crates.io`)
